---
title: "Barragens de mineração em `r params$estado`"
author: "Bea + R-Ladies GYN"
date: "2023-04-29"
output: html_document
theme: minty
params:
  estado: "PR"
embed-resources: true
knitr:
  opts_chunk: 
    message: false
    warning: false
    echo: false
lang: pt    
---

```{r}
#| eval: false
link_sigbm <-  "https://app.anm.gov.br/SIGBM/Publico/ClassificacaoNacionalDaBarragem/ExportarExcel"

httr::POST(link_sigbm,
           httr::write_disk("sigbm.xlsx", overwrite = TRUE))
```

```{r}
library(tidyverse)

barragens <- readxl::read_excel("sigbm.xlsx", skip = 3) |> 
  janitor::clean_names()

barragens_filtradas <- barragens |> 
  filter(uf == params$estado)

base_nome_estado <- abjData::muni |> 
  distinct(uf_nm, uf_sigla, regiao_nm) |> 
  filter(uf_sigla == params$estado)
```

O estado de `r base_nome_estado$uf_nm`, localizado na região `r base_nome_estado$regiao_nm` do Brasil, conta com **`r nrow(barragens_filtradas)`** barragens cadastradas no SIGBM.

## Barragens por dano potencial associado (DPA)

```{r}
#| label: grafico-dpa
#| fig-align: "center"
barragens_filtradas |> 
  dplyr::count(dano_potencial_associado) |> 
  dplyr::mutate(dpa = factor(dano_potencial_associado, c("N/A", "Baixo", "Médio", "Alto"))) |> 
  ggplot() +
  geom_col(aes(x = dpa, y = n), fill = "lightblue") +
  theme_minimal() +
  labs(y = "Quantidade", x = "Dano potencial associado")
```

## Barragens cadastradas no [SIGBM](https://app.anm.gov.br/SIGBM/Publico/ClassificacaoNacionalDaBarragem)

```{r}
#| label: tabela
barragens_filtradas |> 
  select(municipio, nome_da_barragem, nome_do_empreendedor) |> 
  arrange(municipio, nome_do_empreendedor) |> 
  knitr::kable(col.names = c("Município", "Barragem", "Empreendedor"))
```
